services:
  postgres:
    image: postgres:15-alpine
    container_name: l1tter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: l1tter_db
      POSTGRES_USER: l1tter_user
      POSTGRES_PASSWORD: l1tter_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - l1tter-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U l1tter_user -d l1tter_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: l1tter-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - l1tter-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  l1tter-network:
    driver: bridge
